language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

dist: bionic

script:
  - pytest test/*.py
  - pycodestyle
